### ISSUE TITLE
Typo in Your First Template

### ISSUE THREAD

**Issue by moltar** [eta-dev/eta-docs#59]
https://github.com/eta-dev/eta-docs/blob/77f7eaf72d1c418cd72824c167b2a6b2ecc2ad87/docs/learn/first-template.md?plain=1#L12

Should be:

```ts
Eta.render('The answer to everything is <%= it.answer %>', { answer: 42 })
```

**Comment by nebrelbug** [comment]
Thanks for pointing that out! I just fixed it.
